#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.certification.yml"
EVIDENCE_DIR="${ROOT_DIR}/verification/certification"
mkdir -p "${EVIDENCE_DIR}"

if ! command -v docker >/dev/null 2>&1; then
  echo 'Docker is required to start the certification stack.' >&2
  exit 2
fi

required_vars=(JWT_PRIVATE_KEY_B64 JWT_PUBLIC_KEY_B64 ENCRYPTION_KEY_HEX SEED_ADMIN_EMAIL SEED_ADMIN_PASSWORD)
for name in "${required_vars[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    echo "Certification requires ${name} to be set; no default secret is generated by this script." >&2
    exit 2
  fi
done

export DATABASE_URL="${DATABASE_URL:-postgresql://uniportal_cert:uniportal_cert_only@localhost:55433/uniportal_cert}"
export DATABASE_DIRECT_URL="${DATABASE_DIRECT_URL:-${DATABASE_URL}}"
export MIGRATE_DATABASE_URL="${MIGRATE_DATABASE_URL:-${DATABASE_URL}}"
export REDIS_URL="${REDIS_URL:-redis://localhost:56380}"
export S3_ENDPOINT_URL="${S3_ENDPOINT_URL:-http://localhost:59000}"
export S3_UPLOADS_BUCKET="${S3_UPLOADS_BUCKET:-uniportal-cert-uploads}"
export SMTP_HOST="${SMTP_HOST:-localhost}"
export SMTP_PORT="${SMTP_PORT:-51025}"

printf '%s\n' 'Starting certification dependencies.'
docker compose -f "${COMPOSE_FILE}" up -d postgres-cert redis-cert minio-cert mailpit-cert

docker compose -f "${COMPOSE_FILE}" ps > "${EVIDENCE_DIR}/compose-ps.txt"
printf '%s\n' 'Certification dependencies started.'
printf 'DATABASE_URL=%s\nREDIS_URL=%s\nS3_ENDPOINT_URL=%s\nSMTP_HOST=%s\nSMTP_PORT=%s\n' \
  "${DATABASE_URL}" "${REDIS_URL}" "${S3_ENDPOINT_URL}" "${SMTP_HOST}" "${SMTP_PORT}" > "${EVIDENCE_DIR}/effective-endpoints.txt"

cat > "${EVIDENCE_DIR}/README.md" <<'EOF'
# UniPortal certification stack evidence

This directory is generated by `scripts/verify/start-certification-stack.sh`. The stack is ephemeral except for the named MinIO volume. It provides PostgreSQL, Redis, MinIO-compatible object storage, and Mailpit. It does not constitute payment-provider certification, RLS certification, privacy compliance, or institutional production approval.

Required next steps are database migration and role bootstrap, Prisma seed, API/worker startup, RLS matrix tests, object upload completion tests, payment sandbox adapter tests, privacy erasure tests, browser tests, performance tests, backup/restore tests, and independent sign-off.
EOF
