'use client';

import { useEffect, useMemo, useState } from 'react';
import { apiClient, ApiClientError } from '@/lib/api-client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Ref = { id:string; name:string; code?:string|null; iso2?:string|null; iso3?:string|null; type?:string; level?:number; parentId?:string|null };
type Cycle = { id:string; academicYear:string; cycleName:string; admissionType:string; openDate:string; closeDate:string; utmeMinScore:number|null };
type Programme = { id:string; name:string; code:string; degreeType:string; durationYears:number; department:{name:string; faculty:{name:string}} };
type ExamAuthority = { id:string; code:string; name:string };
type ExamType = { id:string; authorityId:string; code:string; name:string; candidateLabel?:string|null };

type FormState = {
  firstName:string; lastName:string; middleName:string; dateOfBirth:string; gender:string; nationality:string;
  countryOfOriginId:string; stateOfOriginId:string; lgaOfOriginId:string; stateOfOrigin:string; lga:string; phone:string; email:string; admissionCycleId:string;
  programmeChoice1Id:string; programmeChoice2Id:string; programmeChoice3Id:string; jambRegNo:string; jambScore:string; declarationAccepted:boolean;
};
const initial: FormState = { firstName:'',lastName:'',middleName:'',dateOfBirth:'',gender:'',nationality:'',countryOfOriginId:'',stateOfOriginId:'',lgaOfOriginId:'',stateOfOrigin:'',lga:'',phone:'',email:'',admissionCycleId:'',programmeChoice1Id:'',programmeChoice2Id:'',programmeChoice3Id:'',jambRegNo:'',jambScore:'',declarationAccepted:false };
const grades = ['A1','B2','B3','C4','C5','C6','D7','E8','F9'];

export default function ApplyPage() {
  const [cycles,setCycles]=useState<Cycle[]>([]); const [programmes,setProgrammes]=useState<Programme[]>([]);
  const [countries,setCountries]=useState<Ref[]>([]); const [originStates,setOriginStates]=useState<Ref[]>([]); const [originLgas,setOriginLgas]=useState<Ref[]>([]);
  const [addressCountries,setAddressCountries]=useState<Ref[]>([]); const [addressRegions,setAddressRegions]=useState<Ref[]>([]); const [addressLgas,setAddressLgas]=useState<Ref[]>([]);
  const [authorities,setAuthorities]=useState<ExamAuthority[]>([]); const [examTypesByAuthority,setExamTypesByAuthority]=useState<Record<string,ExamType[]>>({}); const [subjects,setSubjects]=useState<Ref[]>([]);
  const [form,setForm]=useState<FormState>(initial); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState('');
  const [loadError,setLoadError]=useState(''); const [loadAttempt,setLoadAttempt]=useState(0);
  const [success,setSuccess]=useState<{applicationNo:string;completionPercent:number;trackingToken:string}|null>(null);
  const [olevel,setOlevel]=useState([{subjectId:'',grade:'',authorityId:'',examTypeId:'',examYear:new Date().getFullYear(),sittingNumber:1,candidateCategory:''}]);
  const [secondSitting,setSecondSitting]=useState(false);
  const [address,setAddress]=useState({line1:'',city:'',countryId:'',regionId:'',localAreaId:'',regionName:'',localAreaName:''});
  const [guardian,setGuardian]=useState({fullName:'',relationship:'',phone:'',email:'',occupation:'',address:''});
  const [emergencyContact,setEmergencyContact]=useState({fullName:'',relationship:'',phone:'',email:'',occupation:'',address:''});
  const [previousEducation,setPreviousEducation]=useState([{institution:'',qualification:'',programme:'',startYear:'',endYear:'',gradeOrCgpa:'',certificateNo:''}]);

  useEffect(()=>{ setLoading(true); setLoadError(''); Promise.all([
    apiClient.get<Cycle[]>('/admissions/public/cycles'),apiClient.get<Programme[]>('/admissions/public/programmes'),apiClient.get<Ref[]>('/admissions/public/reference/countries'),
    apiClient.get<ExamAuthority[]>('/admissions/public/reference/examination-authorities'),apiClient.get<Ref[]>('/admissions/public/reference/subjects')
  ]).then(([c,p,co,a,s])=>{setCycles(c);setProgrammes(p);setCountries(co);setAddressCountries(co);setAuthorities(a);setSubjects(s);const ng=co.find(x=>x.iso2==='NG');if(ng)setForm(f=>({...f,countryOfOriginId:ng.id,nationality:'Nigerian'}));setAddress(x=>({...x,countryId:ng?.id??''}));setLoading(false);}).catch(()=>{setLoadError('Application services are temporarily unavailable. Please retry in a moment or contact the Admissions Office if the problem continues.');setLoading(false);});},[loadAttempt]);

  const selectedCycle=useMemo(()=>cycles.find(c=>c.id===form.admissionCycleId),[cycles,form.admissionCycleId]);
  const originCountry=useMemo(()=>countries.find(c=>c.id===form.countryOfOriginId),[countries,form.countryOfOriginId]);
  const addressCountry=useMemo(()=>countries.find(c=>c.id===address.countryId),[countries,address.countryId]);
  const set=(key:keyof FormState,value:string|boolean)=>setForm(f=>({...f,[key]:value}));

  useEffect(()=>{ if(!form.countryOfOriginId){setOriginStates([]);return;} apiClient.get<Ref[]>(`/admissions/public/reference/divisions?countryId=${form.countryOfOriginId}`).then(setOriginStates).catch(()=>setOriginStates([])); setForm(f=>({...f,stateOfOriginId:'',lgaOfOriginId:''}));},[form.countryOfOriginId]);
  useEffect(()=>{ if(!form.stateOfOriginId){setOriginLgas([]);return;} apiClient.get<Ref[]>(`/admissions/public/reference/divisions?countryId=${form.countryOfOriginId}&parentId=${form.stateOfOriginId}`).then(setOriginLgas).catch(()=>setOriginLgas([])); setForm(f=>({...f,lgaOfOriginId:''}));},[form.stateOfOriginId]);
  useEffect(()=>{ if(!address.countryId){setAddressRegions([]);return;} apiClient.get<Ref[]>(`/admissions/public/reference/divisions?countryId=${address.countryId}`).then(setAddressRegions).catch(()=>setAddressRegions([])); setAddress(a=>({...a,regionId:'',localAreaId:''}));},[address.countryId]);
  useEffect(()=>{ if(!address.regionId){setAddressLgas([]);return;} apiClient.get<Ref[]>(`/admissions/public/reference/divisions?countryId=${address.countryId}&parentId=${address.regionId}`).then(setAddressLgas).catch(()=>setAddressLgas([])); setAddress(a=>({...a,localAreaId:''}));},[address.regionId]);


  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!form.declarationAccepted){setError('Please accept the declaration before submitting.');return;}if(!form.countryOfOriginId){setError('Select your country of origin.');return;}if(originCountry?.iso2==='NG'&&(!form.stateOfOriginId||!form.lgaOfOriginId)){setError('Select your Nigerian state and LGA of origin.');return;}setSubmitting(true);try{const result=await apiClient.post<{id:string;applicationNo:string;completionPercent:number;trackingToken:string}>('/admissions/apply',{...form,middleName:form.middleName||undefined,stateOfOrigin:form.stateOfOrigin||undefined,lga:form.lga||undefined,programmeChoice2Id:form.programmeChoice2Id||undefined,programmeChoice3Id:form.programmeChoice3Id||undefined,jambRegNo:form.jambRegNo||undefined,jambScore:form.jambScore?Number(form.jambScore):undefined,residentialAddress:address.line1?{line1:address.line1,city:address.city,countryId:address.countryId,regionId:address.regionId||undefined,localAreaId:address.localAreaId||undefined,state:address.regionName||undefined,lga:address.localAreaName||undefined}:undefined,guardian:guardian.fullName?guardian:undefined,emergencyContact:emergencyContact.fullName?emergencyContact:undefined,previousEducation:previousEducation.filter(e=>e.institution.trim()&&e.qualification.trim()).map(e=>({...e,startYear:e.startYear?Number(e.startYear):undefined,endYear:e.endYear?Number(e.endYear):undefined})),oLevelResults:olevel.map(r=>({subjectId:r.subjectId,grade:r.grade,examType:(authorities.find(a=>a.id===r.authorityId)?.code==='WAEC'?'WAEC':authorities.find(a=>a.id===r.authorityId)?.code==='NECO'?'NECO':authorities.find(a=>a.id===r.authorityId)?.code==='NABTEB'?'NABTEB':authorities.find(a=>a.id===r.authorityId)?.code==='NBAIS'?'NBAIS':'GCE'),examinationAuthorityId:r.authorityId||undefined,examinationTypeId:r.examTypeId||undefined,candidateCategory:r.candidateCategory||undefined,examYear:r.examYear,sittingNumber:r.sittingNumber,subject:subjects.find(s=>s.id===r.subjectId)?.name||''})).filter(r=>r.subjectId&&r.grade&&r.examinationAuthorityId&&r.examinationTypeId)},{idempotencyKey:crypto.randomUUID()});setSuccess(result);}catch(e){setError(e instanceof ApiClientError?e.message:e instanceof Error?e.message:'Application could not be submitted.');}finally{setSubmitting(false);}}

  if(success)return <main className="min-h-screen bg-background px-4 py-10"><Card className="mx-auto max-w-xl"><CardHeader><CardTitle>Application submitted successfully</CardTitle></CardHeader><CardContent className="space-y-4"><p>Your application has been received. Keep your application number safe.</p><div className="rounded-lg border p-4 text-center"><div className="text-xs text-muted-foreground">Application number</div><div className="mt-1 font-mono text-2xl font-semibold">{success.applicationNo}</div><div className="mt-2 text-sm text-muted-foreground">Completion recorded: {success.completionPercent}%</div></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-amber-900">Private tracking credential</div><div className="mt-2 break-all font-mono text-xs text-amber-950">{success.trackingToken}</div><p className="mt-2 text-sm text-amber-900">Save this credential securely. It will not be shown again and is required with your application number to check status.</p></div></CardContent></Card></main>;
  const selectClass='mt-1 flex h-10 w-full rounded-md border bg-background px-3 text-sm';
  return <main className="min-h-screen bg-background px-4 py-8"><div className="mx-auto max-w-5xl space-y-5"><header><h1 className="text-3xl font-bold">University Admission Application</h1><p className="mt-1 text-muted-foreground">Choose standardized information where available. Only enter free text where the university genuinely needs it.</p></header>{error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <Card><CardHeader><CardTitle>Application details</CardTitle></CardHeader><CardContent>{loading?<p>Loading application options…</p>:loadError?<div className="space-y-3" role="alert"><p>{loadError}</p><Button type="button" variant="outline" onClick={()=>setLoadAttempt((n)=>n+1)}>Retry loading application options</Button></div>:cycles.length===0?<p>No admission cycle is currently open. Please check back when the next admission window is announced.</p>:<form onSubmit={submit} className="space-y-7">
    <section className="grid gap-4 md:grid-cols-2"><div><Label>Admission cycle</Label><select required value={form.admissionCycleId} onChange={e=>set('admissionCycleId',e.target.value)} className={selectClass}><option value="">Select cycle</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.cycleName} — {c.academicYear} ({c.admissionType})</option>)}</select></div><div><Label>Admission type</Label><Input value={selectedCycle?.admissionType??''} readOnly className="mt-1" /></div></section>
    <section><h2 className="mb-3 font-semibold">Personal information</h2><div className="grid gap-4 md:grid-cols-3"><div><Label>First name</Label><Input required value={form.firstName} onChange={e=>set('firstName',e.target.value)}/></div><div><Label>Last name</Label><Input required value={form.lastName} onChange={e=>set('lastName',e.target.value)}/></div><div><Label>Middle name</Label><Input value={form.middleName} onChange={e=>set('middleName',e.target.value)}/></div><div><Label>Date of birth</Label><Input required type="date" value={form.dateOfBirth} onChange={e=>set('dateOfBirth',e.target.value)}/></div><div><Label>Gender</Label><select required value={form.gender} onChange={e=>set('gender',e.target.value)} className={selectClass}><option value="">Select</option><option>Female</option><option>Male</option><option>Prefer not to say</option></select></div><div><Label>Nationality</Label><select required value={form.countryOfOriginId} onChange={e=>{const c=countries.find(x=>x.id===e.target.value);set('countryOfOriginId',e.target.value);set('stateOfOriginId','');set('lgaOfOriginId','');set('stateOfOrigin','');set('lga','');set('nationality',c?.iso2==='NG'?'Nigerian':c?.name??'')}} className={selectClass}><option value="">Select country</option>{countries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><Label>State / Province / Region of origin</Label>{originStates.length>0?<select value={form.stateOfOriginId} onChange={e=>set('stateOfOriginId',e.target.value)} className={selectClass}><option value="">Select region</option>{originStates.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>:<Input placeholder="Enter region only when no standardized list exists" value={form.stateOfOrigin} onChange={e=>set('stateOfOrigin',e.target.value)}/>}</div>{originCountry?.iso2==='NG'?<div><Label>LGA of origin</Label><select required value={form.lgaOfOriginId} onChange={e=>set('lgaOfOriginId',e.target.value)} className={selectClass}><option value="">Select LGA</option>{originLgas.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>:<div><Label>Local administrative area (optional)</Label><Input placeholder="Enter only when required" value={form.lga} onChange={e=>set('lga',e.target.value)}/></div>}</div></section>
    <section><h2 className="mb-3 font-semibold">Contact</h2><div className="grid gap-4 md:grid-cols-2"><div><Label>Mobile number</Label><Input required type="tel" placeholder={originCountry?.iso2==='NG'?'08012345678 or +2348012345678':'+447911123456'} value={form.phone} onChange={e=>set('phone',e.target.value)}/></div><div><Label>Email</Label><Input required type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></div></div></section>
    <section><h2 className="mb-3 font-semibold">Programme choices</h2><div className="grid gap-4 md:grid-cols-3">{(['programmeChoice1Id','programmeChoice2Id','programmeChoice3Id'] as const).map((key,i)=><div key={key}><Label>{i===0?'First choice':`${i+1}${i===1?'nd':'rd'} choice`} {i===0?'*':'(optional)'}</Label><select required={i===0} value={form[key]} onChange={e=>set(key,e.target.value)} className={selectClass}><option value="">Select programme</option>{programmes.map(p=><option key={p.id} value={p.id}>{p.code} — {p.name}</option>)}</select></div>)}</div></section>
    {selectedCycle?.admissionType==='UTME'&&<section><h2 className="mb-3 font-semibold">JAMB / UTME</h2><div className="grid gap-4 md:grid-cols-2"><div><Label>JAMB registration number</Label><Input required value={form.jambRegNo} onChange={e=>set('jambRegNo',e.target.value)}/></div><div><Label>UTME score</Label><Input type="number" min={0} max={400} value={form.jambScore} onChange={e=>set('jambScore',e.target.value)}/></div></div></section>}
    <section><h2 className="mb-3 font-semibold">Residential address</h2><div className="grid gap-4 md:grid-cols-3"><div className="md:col-span-2"><Label>Address</Label><Input required value={address.line1} onChange={e=>setAddress(a=>({...a,line1:e.target.value}))}/></div><div><Label>City / town</Label><Input required value={address.city} onChange={e=>setAddress(a=>({...a,city:e.target.value}))}/></div><div><Label>Country</Label><select required value={address.countryId} onChange={e=>setAddress(a=>({...a,countryId:e.target.value,regionId:'',localAreaId:'',regionName:'',localAreaName:''}))} className={selectClass}>{addressCountries.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><Label>State / Province / Region</Label>{addressRegions.length>0?<select value={address.regionId} onChange={e=>setAddress(a=>({...a,regionId:e.target.value}))} className={selectClass}><option value="">Select</option>{addressRegions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>:<Input placeholder="Enter region only when no standardized list exists" value={address.regionName} onChange={e=>setAddress(a=>({...a,regionName:e.target.value}))} />}</div>{addressCountry?.iso2==='NG'&&<div><Label>LGA</Label><select value={address.localAreaId} onChange={e=>setAddress(a=>({...a,localAreaId:e.target.value}))} className={selectClass}><option value="">Select LGA</option>{addressLgas.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>}</div></section>
    <section><h2 className="mb-3 font-semibold">Parent / guardian</h2><div className="grid gap-4 md:grid-cols-2"><div><Label>Full name</Label><Input value={guardian.fullName} onChange={e=>setGuardian(g=>({...g,fullName:e.target.value}))}/></div><div><Label>Relationship</Label><Input value={guardian.relationship} onChange={e=>setGuardian(g=>({...g,relationship:e.target.value}))}/></div><div><Label>Phone</Label><Input value={guardian.phone} onChange={e=>setGuardian(g=>({...g,phone:e.target.value}))}/></div><div><Label>Email (optional)</Label><Input type="email" value={guardian.email} onChange={e=>setGuardian(g=>({...g,email:e.target.value}))}/></div></div></section>
    <section><h2 className="mb-3 font-semibold">Emergency contact</h2><div className="grid gap-4 md:grid-cols-2"><div><Label>Full name</Label><Input value={emergencyContact.fullName} onChange={e=>setEmergencyContact(c=>({...c,fullName:e.target.value}))}/></div><div><Label>Relationship</Label><Input value={emergencyContact.relationship} onChange={e=>setEmergencyContact(c=>({...c,relationship:e.target.value}))}/></div><div><Label>Phone</Label><Input value={emergencyContact.phone} onChange={e=>setEmergencyContact(c=>({...c,phone:e.target.value}))}/></div><div><Label>Email (optional)</Label><Input type="email" value={emergencyContact.email} onChange={e=>setEmergencyContact(c=>({...c,email:e.target.value}))}/></div><div className="md:col-span-2"><Label>Address (optional)</Label><Input value={emergencyContact.address} onChange={e=>setEmergencyContact(c=>({...c,address:e.target.value}))}/></div></div></section>
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">Previous education</h2><p className="text-xs text-muted-foreground">Add completed schools or qualifications relevant to this application.</p></div><Button type="button" variant="outline" size="sm" onClick={()=>setPreviousEducation(xs=>[...xs,{institution:'',qualification:'',programme:'',startYear:'',endYear:'',gradeOrCgpa:'',certificateNo:''}])}>Add education</Button></div><div className="space-y-3">{previousEducation.map((e,i)=><div key={i} className="grid gap-2 rounded-lg border p-3 md:grid-cols-2"><div><Label>Institution</Label><Input value={e.institution} onChange={ev=>setPreviousEducation(xs=>xs.map((x,j)=>j===i?{...x,institution:ev.target.value}:x))}/></div><div><Label>Qualification</Label><Input value={e.qualification} onChange={ev=>setPreviousEducation(xs=>xs.map((x,j)=>j===i?{...x,qualification:ev.target.value}:x))}/></div><div><Label>Programme (optional)</Label><Input value={e.programme} onChange={ev=>setPreviousEducation(xs=>xs.map((x,j)=>j===i?{...x,programme:ev.target.value}:x))}/></div><div><Label>Grade / CGPA (optional)</Label><Input value={e.gradeOrCgpa} onChange={ev=>setPreviousEducation(xs=>xs.map((x,j)=>j===i?{...x,gradeOrCgpa:ev.target.value}:x))}/></div><div><Label>Start year (optional)</Label><Input type="number" min={1950} max={2100} value={e.startYear} onChange={ev=>setPreviousEducation(xs=>xs.map((x,j)=>j===i?{...x,startYear:ev.target.value}:x))}/></div><div><Label>End year (optional)</Label><Input type="number" min={1950} max={2100} value={e.endYear} onChange={ev=>setPreviousEducation(xs=>xs.map((x,j)=>j===i?{...x,endYear:ev.target.value}:x))}/></div></div>)}</div></section>
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-semibold">O'Level results</h2><p className="text-xs text-muted-foreground">Select the examination authority, examination type, subject and grade. Do not type standardized values.</p></div><label className="text-sm"><input type="checkbox" checked={secondSitting} onChange={e=>setSecondSitting(e.target.checked)}/> Add second sitting</label></div><div className="space-y-3">{olevel.map((r,i)=>{const types=examTypesByAuthority[r.authorityId]??[];return <div key={i} className="grid gap-2 rounded-lg border p-3 md:grid-cols-6"><select value={r.authorityId} onChange={e=>{const authorityId=e.target.value;setOlevel(xs=>xs.map((x,j)=>j===i?{...x,authorityId,examTypeId:'',candidateCategory:''}:x));if(authorityId&&!examTypesByAuthority[authorityId])apiClient.get<ExamType[]>(`/admissions/public/reference/examination-types?authorityId=${authorityId}`).then(v=>setExamTypesByAuthority(m=>({...m,[authorityId]:v}))).catch(()=>undefined);}} className={selectClass}><option value="">Exam body</option>{authorities.map(a=><option key={a.id} value={a.id}>{a.code}</option>)}</select><select value={r.examTypeId} onChange={e=>setOlevel(xs=>xs.map((x,j)=>j===i?{...x,examTypeId:e.target.value}:x))} className={selectClass}><option value="">Exam type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select value={r.subjectId} onChange={e=>setOlevel(xs=>xs.map((x,j)=>j===i?{...x,subjectId:e.target.value}:x))} className={selectClass}><option value="">Subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={r.grade} onChange={e=>setOlevel(xs=>xs.map((x,j)=>j===i?{...x,grade:e.target.value}:x))} className={selectClass}><option value="">Grade</option>{grades.map(g=><option key={g}>{g}</option>)}</select><Input type="number" min={1990} max={2100} value={r.examYear} onChange={e=>setOlevel(xs=>xs.map((x,j)=>j===i?{...x,examYear:Number(e.target.value)}:x))}/><select value={r.sittingNumber} onChange={e=>setOlevel(xs=>xs.map((x,j)=>j===i?{...x,sittingNumber:Number(e.target.value)}:x))} className={selectClass} disabled={!secondSitting}><option value={1}>1st sitting</option><option value={2}>2nd sitting</option></select></div>})}</div><Button type="button" variant="outline" size="sm" className="mt-2" onClick={()=>setOlevel(xs=>[...xs,{subjectId:'',grade:'',authorityId:'',examTypeId:'',examYear:new Date().getFullYear(),sittingNumber:secondSitting?2:1,candidateCategory:''}])}>Add subject</Button></section>
    <section className="rounded-lg border p-4"><label className="flex gap-3 text-sm"><input className="mt-1" type="checkbox" checked={form.declarationAccepted} onChange={e=>set('declarationAccepted',e.target.checked)}/><span>I confirm that the information supplied is accurate and understand that admission is subject to verification and approved university requirements.</span></label></section>
    <div className="flex justify-end"><Button type="submit" loading={submitting} disabled={!form.admissionCycleId}>Submit application</Button></div>
  </form>}</CardContent></Card></div></main>;
}
